spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    targetRevision: HEAD

  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

ingress:
  domain: localhost

config:
  tag: latest
  branch: HEAD
rcs:
  tag: latest
  branch: HEAD
rs:
  tag: latest
  branch: HEAD
ui:
  branch: HEAD
  tag: latest

mongodb:
  auth:
    enabled: false