{{- if and (eq .Values.use.fidc.platform "true") (eq .Values.use.fidc.initializer "true") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-init-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: _infra/helm/securebanking-openbanking-uk-fidc-initializer
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer
    targetRevision: HEAD
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
{{- end }}
