apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: mongodb
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: auth.enabled
        value: "{{ .Values.mongodb.auth.enabled }}"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.15.1
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
