apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rcs-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: ingress.domain
        value: {{ .Values.ingress.domain }}
      - name: deployment.imageOverride.tag
        value: {{ .Values.rcs.tag }}
      - name: deployment.cors.originEnds
        value: {{ .Values.cors.originEnds }}
    path: _infra/helm/securebanking-openbanking-uk-rcs
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs
    targetRevision: {{ .Values.rcs.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
