apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-init-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: environment.type
        value: {{ .Values.environment.type }}     
      - name: environment.cdmadminpassword
        value: {{ .Values.test-init.cdmadminpassword }}
    path: _infra/helm/securebanking-test-data-initializer
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-test-data-initializer
    targetRevision: HEAD
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
