apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-sensor
  annotations:
    workflows.argoproj.io/description: >-
      This task takes the body of a git event request and 
      extracts environment data from it
    workflows.argoproj.io/tags: argocd
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  entrypoint: git-sensor
  arguments:
    parameters:
      - name: pr-number
      - name: application-name
      - name: branch
        value: HEAD
      - name: actor
      - name: tag
        value: latest
      - name: namespace
        value: dev
  templates:
  - name: git-sensor
    steps:
    - - name: parse-body
        template: git-body
        arguments:
          parameters:
          - name: pr-number
            value: "{{workflow.parameters.pr-number}}"
          - name: application-name
            value: "{{workflow.parameters.application-name}}"
          - name: actor
            value: "{{workflow.parameters.actor}}"
    - - name: trigger-sync
        template: sync-git
        arguments:
          parameters:
          - name: application-name
            value: "{{steps.parse-body.outputs.parameters.application-name}}"
          - name: tag
            value: "{{steps.parse-body.outputs.parameters.tag}}"
          - name: branch
            value: "{{workflow.parameters.branch}}"

  - name: git-body
    inputs:
      parameters:
      - name: pr-number
      - name: application-name
      - name: branch
        value: HEAD
      - name: actor
    script:
      image: dwdraju/alpine-curl-jq
      command: [bash]
      source: |
        name="$(echo '{{inputs.parameters.application-name}}' | rev | cut -d '-' -f 1 | rev)"
        echo 'pr-{{inputs.parameters.pr-number}}' > /tmp/tag.txt
        echo $name > /tmp/service.txt
        echo '{{inputs.parameters.actor}}' > /tmp/actor.txt
    outputs:
      parameters:
      - name: tag
        valueFrom:
          path: /tmp/tag.txt
      - name: application-name
        valueFrom:
          path: /tmp/service.txt
  
  - name: sync-git
    inputs:
      parameters:
      - name: application-name
      - name: namespace
      - name: tag
      - name: branch
    steps:
      - - name: sync
          templateRef:
            name: sync-application-via-parent
            template: sync-git
          arguments:
            parameters:
            - name: application-name
              value: "{{inputs.parameters.application-name}}"
            - name: namespace
              value: "{{workflow.parameters.namespace}}"
            - name: tag
              value: "{{inputs.parameters.tag}}"
            - name: branch
              value: "{{inputs.parameters.branch}}"
  