apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argocd-sync-and-wait
  annotations:
    workflows.argoproj.io/description: >-
      This task syncs (deploys) an Argo CD application and waits for it to be healthy.

      To do so, it requires the address of the Argo CD server and
      authentication via username/password
    workflows.argoproj.io/tags: argocd
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  entrypoint: argocd-sync-and-wait
  templates:
  - name: sync-application-via-parent
    inputs:
      parameters:
      - name: argocd-version
        value: v2.0.0
      - name: application-name
      - name: parent-name
        value: securebanking
      - name: namespace
        value: dev
      - name: tag
        value: latest
      - name: branch
        value: HEAD
    script:
      image: argoproj/argocd:{{inputs.parameters.argocd-version}}
      command: [bash]
      env:
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: argo-bot-token
              key: token
        - name: ARGOCD_SERVER
          valueFrom:
            configMapKeyRef:
              name: argocd-cm
              key: cli-server
      source: |
        #!/bin/bash

        set -euo pipefail
        argocd app set {{inputs.parameters.parent-name}}-{{inputs.parameters.namespace}} -p {{inputs.parameters.application-name}}.tag={{inputs.parameters.tag}} -p {{inputs.parameters.application-name}}.branch={{inputs.parameters.branch}}
        argocd app delete {{inputs.parameters.application-name}}-{{inputs.parameters.parent-name}}-{{inputs.parameters.namespace}} --cascade --yes || true
  
  - name: sync-parent
    inputs:
      parameters:
      - name: argocd-version
        value: v2.0.0
      - name: parent-name
        value: securebanking
      - name: namespace
        value: dev
    script:
      image: argoproj/argocd:{{inputs.parameters.argocd-version}}
      command: [bash]
      env:
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: argo-bot-token
              key: token
        - name: ARGOCD_SERVER
          valueFrom:
            configMapKeyRef:
              name: argocd-cm
              key: cli-server
      source: |
        #!/bin/bash

        set -euo pipefail
        argocd app sync {{inputs.parameters.parent-name}}-{{inputs.parameters.namespace}}
