apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securebanking-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.argoNamespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Release.Name }}
  source:
    helm:
      parameters:
      - name: ingress.domain
        value: {{ .Values.ingress.domain }}
    path: argo/cd/services
    repoURL: https://github.com/SecureBankingAccessToolkit/sbat-cd
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true