apiVersion: batch/v1
kind: Job
metadata:
  name: apply-gcr-secret-to-sa
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      volumes:
        - name: argo-configuration
          configMap: 
            name: deployment
      serviceAccountName: job-sa
      restartPolicy: Never
      containers:
        - name: gcloud
          image: google/cloud-sdk
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              kubectl patch sa {{ .Values.serviceAccount }} -p '{"imagePullSecrets": [{"name": "{{ .Values.imageRepoSecret.name }}"}]}'
              kubectl apply -f /opt/deploymentConfiguration.yaml -n {{ .Values.argoNamespace }}
          volumeMounts:
            - name: argo-configuration
              mountPath: /opt
              readOnly: true
