apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment
data:
  deploymentConfiguration.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: securebanking-{{ .Release.Name }}
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: {{ .Values.argoNamespace }}
        server: {{ .Values.spec.destination.server }}
      project: {{ .Values.spec.project }}
      source:
        helm:
          parameters:
          - name: ingress.domain
            value: {{ .Values.ingress.domain }}
        path: argo/cd/services
        repoURL: https://github.com/SecureBankingAccessToolkit/sbat-cd
        targetRevision: {{ .Values.spec.source.targetRevision }}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
  gcr-secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: gcr-secret
      annotations:
        replicator.v1.mittwald.de/replicate-from: {{ .Values.imageRepoSecret.namespace }}/{{ .Values.imageRepoSecret.name }}
    type: kubernetes.io/dockerconfigjson
    data:
      .dockerconfigjson: e30K