apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-sa-role
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete