apiVersion: batch/v1
kind: Job
metadata:
  name: apply-gcr-secret-to-sa
spec:
  template:
    spec:
      serviceAccountName: job-sa
      restartPolicy: Never
      containers:
        - name: gcloud
          image: google/cloud-sdk
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              kubectl patch sa {{ .Values.serviceAccount }} -p '{"imagePullSecrets": [{"name": "{{ .Values.imageRepoSecret.name }}"}]}'
