spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    targetRevision: argo-sync

ingress:
  domain: localhost

externalCert:
  projectId: example-project
